version : "3.7"

services:
  database_meuprofessor:
    image: postgres
    container_name: database_meuprofessor
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=meuprofessor
    volumes:
      - pgdata:/data/postgres
    network_mode: host
  app: 
    build: .
    container_name: meuprofessor
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    network_mode: host
volumes: 
  pgdata:
    driver: local